// This file was generated by Rcpp::compileAttributes
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// optimGascuel
double optimGascuel(NumericVector params, NumericVector lj, NumericVector li, NumericVector pi_, double threshold, int maxiter);
RcppExport SEXP ALKr_optimGascuel(SEXP paramsSEXP, SEXP ljSEXP, SEXP liSEXP, SEXP pi_SEXP, SEXP thresholdSEXP, SEXP maxiterSEXP) {
BEGIN_RCPP
    Rcpp::RNGScope __rngScope;
    NumericVector params = Rcpp::as<NumericVector >(paramsSEXP);
    NumericVector lj = Rcpp::as<NumericVector >(ljSEXP);
    NumericVector li = Rcpp::as<NumericVector >(liSEXP);
    NumericVector pi_ = Rcpp::as<NumericVector >(pi_SEXP);
    double threshold = Rcpp::as<double >(thresholdSEXP);
    int maxiter = Rcpp::as<int >(maxiterSEXP);
    double __result = optimGascuel(params, lj, li, pi_, threshold, maxiter);
    return Rcpp::wrap(__result);
END_RCPP
}
// finalGascuel
NumericMatrix finalGascuel(NumericVector params, NumericVector lj, NumericVector li, NumericVector pi_, double threshold, int maxiter);
RcppExport SEXP ALKr_finalGascuel(SEXP paramsSEXP, SEXP ljSEXP, SEXP liSEXP, SEXP pi_SEXP, SEXP thresholdSEXP, SEXP maxiterSEXP) {
BEGIN_RCPP
    Rcpp::RNGScope __rngScope;
    NumericVector params = Rcpp::as<NumericVector >(paramsSEXP);
    NumericVector lj = Rcpp::as<NumericVector >(ljSEXP);
    NumericVector li = Rcpp::as<NumericVector >(liSEXP);
    NumericVector pi_ = Rcpp::as<NumericVector >(pi_SEXP);
    double threshold = Rcpp::as<double >(thresholdSEXP);
    int maxiter = Rcpp::as<int >(maxiterSEXP);
    NumericMatrix __result = finalGascuel(params, lj, li, pi_, threshold, maxiter);
    return Rcpp::wrap(__result);
END_RCPP
}
// hoenigC
List hoenigC(List AAk, List FFik, List FFiz, int threshold, int maxiter);
RcppExport SEXP ALKr_hoenigC(SEXP AAkSEXP, SEXP FFikSEXP, SEXP FFizSEXP, SEXP thresholdSEXP, SEXP maxiterSEXP) {
BEGIN_RCPP
    Rcpp::RNGScope __rngScope;
    List AAk = Rcpp::as<List >(AAkSEXP);
    List FFik = Rcpp::as<List >(FFikSEXP);
    List FFiz = Rcpp::as<List >(FFizSEXP);
    int threshold = Rcpp::as<int >(thresholdSEXP);
    int maxiter = Rcpp::as<int >(maxiterSEXP);
    List __result = hoenigC(AAk, FFik, FFiz, threshold, maxiter);
    return Rcpp::wrap(__result);
END_RCPP
}
