# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

optimGascuel <- function(params, lj, li, pi_, threshold, maxiter) {
    .Call('_ALKr_optimGascuel', PACKAGE = 'ALKr', params, lj, li, pi_, threshold, maxiter)
}

finalGascuel <- function(params, lj, li, pi_, threshold, maxiter) {
    .Call('_ALKr_finalGascuel', PACKAGE = 'ALKr', params, lj, li, pi_, threshold, maxiter)
}

hoenigC <- function(AAk, FFik, FFiz, threshold, maxiter) {
    .Call('_ALKr_hoenigC', PACKAGE = 'ALKr', AAk, FFik, FFiz, threshold, maxiter)
}

