# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

optimGascuel <- function(params, lj, li, pi_, threshold, maxiter) {
    .Call('ALKr_optimGascuel', PACKAGE = 'ALKr', params, lj, li, pi_, threshold, maxiter)
}

finalGascuel <- function(params, lj, li, pi_, threshold, maxiter) {
    .Call('ALKr_finalGascuel', PACKAGE = 'ALKr', params, lj, li, pi_, threshold, maxiter)
}

